name: Lint
on:
  pull_request:
    branches:
    - develop

jobs:
  linters:
    name: stylelint
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Set Node.js version
        uses: actions/setup-node@v1

      - name: Install npm dependencies
        run: npm ci

      - name: Lint
        run: gulp lint
